# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: bitso 0.1.5 ruby lib

Gem::Specification.new do |s|
  s.name = "bitso"
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Arturo Diaz"]
  s.date = "2015-08-19"
  s.description = "API wrapper for Bitso, a Mexican Bitcoin Exchange"
  s.email = "me@arturodz.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".rspec",
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bitso.gemspec",
    "lib/bitso.rb",
    "lib/bitso/helper.rb",
    "spec/bitso_spec.rb",
    "spec/collection_spec.rb",
    "spec/fixtures/vcr_cassettes/bitso/balance.yml",
    "spec/fixtures/vcr_cassettes/bitso/order_book.yml",
    "spec/fixtures/vcr_cassettes/bitso/orders/all.yml",
    "spec/fixtures/vcr_cassettes/bitso/orders/buy.yml",
    "spec/fixtures/vcr_cassettes/bitso/orders/sell/failure.yml",
    "spec/fixtures/vcr_cassettes/bitso/ticker.yml",
    "spec/fixtures/vcr_cassettes/bitso/transactions.yml",
    "spec/fixtures/vcr_cassettes/bitso/unconfirmed_user_deposits.yml",
    "spec/fixtures/vcr_cassettes/bitso/user_transactions/all.yml",
    "spec/fixtures/vcr_cassettes/bitso/withdraw_bitcoins/failure.yml",
    "spec/orders_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/bitso_setup.rb",
    "spec/support/vcr.rb",
    "spec/transactions_spec.rb"
  ]
  s.homepage = "http://github.com/arturodz/bitso"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.8"
  s.summary = "API wrapper for Bitso"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<typhoeus>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 4.2.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<typhoeus>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 4.2.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<typhoeus>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 4.2.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

